(function(){function B(){}function x(a,b){return 0==ha.call(a).indexOf("[object "+b)}function v(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function z(a,b){var c,e,d,f;c=1;e=a;b&&(e=e.replace(ia,function(a,b,e,d){e&&c++;f=q;return d||""}));if(f){d=b.split("/");if(c>d)throw Error("attempt to access module beyond root of package: "+a);d.splice(d.length-c,c);return d.concat(e||[]).join("/")}return e}function I(a){var b=a.indexOf("!");return{M:a.substr(b+1),i:0<=b&&a.substr(0,b)}}
function i(){}function t(a,b){i.prototype=a||O;var c=new i;i.prototype=O;for(var e in b)c[e]=b[e];return c}function o(){function a(a,b,d){e.push([a,b,d])}function b(a,b){for(var d,c=0;d=e[c++];)(d=d[a])&&d(b)}var c,e,d;c=this;e=[];d=function(f,c){a=f?function(a){a&&a(c)}:function(a,b){b&&b(c)};d=B;b(f?0:1,c);b=B;e=m};this.t=function(b,d,e){a(b,d,e)};this.f=function(a){c.s=a;d(q,a)};this.d=function(a){c.ga=a;d(y,a)};this.p=function(a){b(2,a)}}function s(a,b,c,e){a instanceof o?a.t(b,c,e):b(a)}function D(a,
b,c){var e;return function(){0<=--a&&b&&(e=b.apply(m,arguments));0==a&&c&&c(e);return e}}function E(){function a(b,d,c,g){var j;j=h.g(p,m,[].concat(b));this.then=b=function(a,b){s(j,function(b){a&&a.apply(m,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(b,d,e){return new a(b,d,e,j)};d&&b(d,c);s(g,function(){h.h(j)})}var b=[].slice.call(arguments),c;x(b[0],"Object")&&(c=b.shift(),p=h.b(c,p),h.v(c));return new a(b[0],b[1],b[2])}function T(a){var b=a.id;if(b==m)if(F!==m)F=
{C:"Multiple anonymous defines in url"};else if(!(b=h.$()))F=a;if(b!=m){var c=k[b];b in k||(c=h.j(b,p).b,c=k[b]=h.z(c,b));if(!(c instanceof o))throw Error("duplicate define: "+b);c.fa=y;h.A(c,a)}}function ja(a){try{return eval(a)}catch(b){}}function U(){var a;a=n[ka]("link");a.rel="stylesheet";a.type="text/css";return a}function la(a,b,c){V.push({url:a,P:b,S:function(){c(Error(W))}});a=X.shift();!a&&Y.length<ma&&(a=n.createElement("style"),Y.push(a),J.appendChild(a));a&&P(a)}function P(a){var b;(b=
V.shift())?(a.onload=function(){b.P();P(a)},a.onerror=function(){b.S();P(a)},a.styleSheet.addImport(b.url)):(a.onload=a.onerror=C,X.push(a))}function Z(a,b,c){if(!G.load){var e,d,f;if(!a.href||n.readyState&&"complete"!=n.readyState)e=y;else{e=y;try{if(d=a.sheet)f=d.cssRules,e=null===f,!e&&"length"in f&&(d.insertRule("-curl-css-test {}",0),d.deleteRule(0),e=q)}catch(g){e=/security|denied/i.test(g.message)}}e?c():a.onload==C||!a.onload||aa(function(){Z(a,b,c)},b)}}function na(a,b,c,e){function d(){if(f.onload!=
C&&f.onload){f.onload=f.onerror=C;var a=function(){!n.readyState||"complete"==n.readyState?b():aa(a,10)};a()}}var f;f=U();f.onload=function(){G.load=G.load||q;d()};Z(f,e,d);f.onerror=function(){G.error=G.error||q;f.onload!=C&&f.onload&&(f.onload=f.onerror=C,c(Error(W)))};f.href=a;J.appendChild(f)}function C(){}var q=!0,y=!1,w=this.window||global,p,K,Q,L=w.document,R=L&&(L.head||L.getElementsByTagName("head")[0]),oa=R&&R.getElementsByTagName("base")[0]||null,ba={},ca={},M={},pa="addEventListener"in
w?{}:{loaded:1,complete:1},O={},ha=O.toString,m,k={},N=y,F,qa=/\?/,da=/^\/|^[^:]+:\/\//,ia=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,ra=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,sa=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,S,h;h={O:function(a,b){return h.m(z(a,b))},m:function(a,b){return b.c&&a in b.c&&b.c[a].ba||a},n:function(a,b){a&&b.K&&0>a.indexOf("/")&&(a=v(b.K)+"/"+a);return a},g:function(a,b,c,e){function d(b){return h.m(z(b,g.id),a)}function f(b,c,f){var l,ea;l=c&&function(a){c.apply(m,
a)};if(x(b,"String")){b=d(b);f=k[b];ea=f instanceof o&&f.a;if(!(b in k))throw Error("Module not resolved: "+b);if(l)throw Error("require(id, callback) not allowed");return ea||f}s(h.h(h.g(a,g.id,b,e)),l,f)}var g;g=new o;g.id=b||"";g.aa=e;g.B=c;g.b=a;g.q=f;f.toUrl=function(b){return h.j(d(b),a).url};g.O=d;return g},z:function(a,b,c){var e,d,f;e=h.g(a,b,m,c);d=e.f;f=D(1,function(a){e.l=a;try{return h.T(e)}catch(b){e.d(b)}});e.f=function(a){s(c||N,function(){d(k[e.id]=f(a))})};e.D=function(a){s(c||N,
function(){e.a&&(f(a),e.p(ca))})};return e},Q:function(a,b,c,e){return h.g(a,c,m,e)},Z:function(a){return a.q},F:function(a){return a.a||(a.a={})},Y:function(a){var b=a.o;b||(b=a.o={id:a.id,uri:h.G(a),exports:h.F(a),config:function(){return a.b}},b.a=b.exports);return b},G:function(a){return a.url||(a.url=h.w(a.q.toUrl(a.id)),a.b)},b:function(a){var b,c,e,d,f,g;b=!a;a&&(h.b=h.J);a||(a={});e=a.apiName||"curl";d=a.apiContext||w;f=a.defineName||"define";g=a.defineContext||w;c=a.overwriteApi;!b&&K&&(w.curl=
K,K=y);if(!b&&!c&&d[e]&&d[e]!=E)throw Error(e+" already exists");d[e]=E;if(!b||!w.define){if(!b&&!c&&f in g&&g[f]!=Q)throw Error(f+" already exists");g[f]=Q=function(){var a=h.X(arguments);T(a)};Q.amd={plugins:q,jQuery:q,curl:"0.7.0"}}return h.J(a)},J:function(a,b){function c(a,b){var e,c,g,A,j;for(j in a){g=a[j];g.name=g.id||g.name||j;A=d;c=I(v(g.name||j));e=c.M;if(c=h.n(c.i,d))(A=f[c])||(A=f[c]=t(d),A.c=t(d.c),A.e=[]),delete a[j];if(b){c=g;var H=void 0;c.path=v(c.path||c.location||"");H=v(c.main)||
"main";"."!=H.charAt(0)&&(H="./"+H);c.ba=z(H,c.name+"/");c.b=c.config;c.b&&(c.b=t(d,c.b))}else c={path:v(g)};c.N=e.split("/").length;e?(A.c[e]=c,A.e.push(e)):A.u=h.L(g,d)}}function e(a){var b=a.c;a.da=RegExp("^("+a.e.sort(function(a,c){return b[c].N-b[a].N}).join("|").replace(/\/|\./g,"\\$&")+")(?=\\/|$)");delete a.e}var d,f,g;b||(b={});d=t(b,a);d.u=d.baseUrl||"";d.K=d.pluginPath||"curl/plugin";d.R=RegExp(d.dontAddFileExt||qa);d.c=t(b.c);f=a.plugins||{};d.plugins=t(b.plugins);for(g in f)d.plugins[h.n(g,
d)]=f[g];f=d.plugins;d.e=[];c(a.paths,y);c(a.packages,q);for(g in f){f[g]=t(d,f[g]);var j=f[g].e;j&&(f[g].e=j.concat(d.e),e(f[g]))}e(d);return d},v:function(a){var b;(b=a&&a.preloads)&&0<b.length&&s(N,function(){N=h.h(h.g(p,m,b,q))})},j:function(a,b){var c,e,d,f;c=b.c;d=da.test(a)?a:a.replace(b.da,function(a){e=c[a]||{};f=e.b;return e.path||""});return{b:f||p,url:h.L(d,b)}},L:function(a,b){var c=b.u;return c&&!da.test(a)?v(c)+"/"+a:a},w:function(a,b){return a+((b||p).R.test(a)?"":".js")},H:function(a,
b,c){var e=L.createElement("script");e.onload=e.onreadystatechange=function(c){c=c||w.event;if("load"==c.type||pa[e.readyState])delete M[a.id],e.onload=e.onreadystatechange=e.onerror="",b()};e.onerror=function(){c(Error("Syntax or http error: "+a.url))};e.type=a.I||"text/javascript";e.charset="utf-8";e.async=!a.ca;e.src=a.url;M[a.id]=e;R.insertBefore(e,oa);return e},U:function(a){var b=[],c;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(ra,"").replace(sa,function(a,d,f){f?c=c==
f?m:c:c||b.push(d);return""});return b},X:function(a){var b,c,e,d,f,g;f=a.length;e=a[f-1];d=x(e,"Function")?e.length:-1;2==f?x(a[0],"Array")?c=a[0]:b=a[0]:3==f&&(b=a[0],c=a[1]);!c&&0<d&&(g=q,c=["require","exports","module"].slice(0,d).concat(h.U(e)));return{id:b,l:c||[],r:0<=d?e:function(){return e},k:g}},T:function(a){var b;b=a.r.apply(a.k?a.a:m,a.l);b===m&&a.a&&(b=a.o?a.a=a.o.a:a.a);return b},A:function(a,b){a.r=b.r;a.k=b.k;a.B=b.l;h.h(a)},h:function(a){function b(a,b,c){g[b]=a;c&&u(a,b)}function c(b,
c){var e,d,f,g;e=D(1,function(a){d(a);l(a,c)});d=D(1,function(a){u(a,c)});f=h.V(b,a);(g=f instanceof o&&f.a)&&d(g);s(f,e,a.d,a.a&&function(a){f.a&&(a==ba?d(f.a):a==ca&&e(f.a))})}function e(){a.f(g)}var d,f,g,j,r,u,l;g=[];f=a.B;j=f.length;0==f.length&&e();u=D(j,b,function(){a.D&&a.D(g)});l=D(j,b,e);for(d=0;d<j;d++)r=f[d],r in S?(l(S[r](a),d,q),a.a&&a.p(ba)):r?c(r,d):l(m,d,q);return a},W:function(a){h.G(a);h.H(a,function(){var b=F;F=m;a.fa!==y&&(!b||b.C?a.d(Error(b&&b.C||"define() missing or duplicated: "+
a.url)):h.A(a,b))},a.d);return a},V:function(a,b){var c,e,d,f,g,j,r,u,l,i;c=b.O;e=b.aa;l=b.b||p;d=I(a);j=d.M;f=d.i?h.m(h.n(z(d.i,b.id),l),l):c(j);r=h.j(f,l);if(d.i)g=f;else if(g=r.b.moduleLoader)j=f,f=g,r=h.j(g,l);d=k[f];f in k||(d=k[f]=h.z(r.b,f,e),d.url=h.w(r.url,d.b),h.W(d));f==g&&(u=new o,i=l.plugins[g]||l,s(d,function(a){var b,d,f;f=a.dynamic;j="normalize"in a?a.normalize(j,c,i)||"":c(j);d=g+"!"+j;b=k[d];if(!(d in k)){b=h.Q(i,d,j,e);f||(k[d]=b);var r=function(a){b.f(a);f||(k[d]=a)};r.resolve=
r;r.reject=r.error=b.d;a.load(j,b.q,r,i)}u!=b&&s(b,u.f,u.d,u.p)},u.d));return u||d},$:function(){var a;if(!x(w.opera,"Opera"))for(var b in M)if("interactive"==M[b].readyState){a=b;break}return a}};S={require:h.Z,exports:h.F,module:h.Y};E.version="0.7.0";p=w.curl;"function"==typeof p?(K=p,p=y):w.curl=m;p=h.b(p);h.v(p);k.curl=E;k["curl/_privileged"]={core:h,cache:k,config:function(){return p},_define:T,_curl:E,Promise:o};var fa=this.document;define("curl/plugin/js",["curl/_privileged"],function(a){function b(b,
c,d){function e(){g||(f<new Date?d():setTimeout(e,10))}var f,g,h;f=(new Date).valueOf()+(b.ea||3E5);d&&b.a&&setTimeout(e,10);h=a.core.H(b,function(){g=q;b.a&&(b.s=ja(b.a));!b.a||b.s?c(h):d()},function(a){g=q;d(a)})}function c(a,e){b(a,function(){var b=d.shift();h=0<d.length;b&&c.apply(null,b);e.f(a.s||q)},function(a){e.d(a)})}var e={},d=[],f=fa&&fa.createElement("script").async==q,g,h;g=a.Promise;return{dynamic:q,load:function(a,i,l,m){function p(a){(l.error||function(a){throw a;})(a)}var k,o,s,t,
n;k=0<a.indexOf("!order");o=a.indexOf("!exports=");s=0<o&&a.substr(o+9);t="prefetch"in m?m.prefetch:q;a=k||0<o?a.substr(0,a.indexOf("!")):a;n=i.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".js":a);n in e?e[n]instanceof g?e[n].t(l,p):l(e[n]):(a={name:a,url:n,ca:k,a:s,ea:m.timeout},e[n]=i=new g,i.t(function(a){e[n]=a;l(a)},p),k&&!f&&h?(d.push([a,i]),t&&(a.I="text/cache",b(a,function(a){a&&a.parentNode.removeChild(a)},function(){}),a.I="")):(h=h||k,c(a,i)))}}});var ka="createElement",aa=this.setTimeout,
n=this.document,J,ta=n&&n.createStyleSheet&&!(10<=n.documentMode),Y=[],X=[],V=[],ma=12,ga,W="HTTP or network error.",G={};n&&(J=n.head||n.getElementsByTagName("head")[0],ga=ta?la:na);define("curl/plugin/css",{normalize:function(a,b){var c,e;if(!a)return a;c=a.split(",");e=[];for(var d=0,f=c.length;d<f;d++)e.push(b(c[d]));return e.join(",")},load:function(a,b,c,e){function d(){0==--i&&c()}function f(a){(c.d||function(a){throw a;})(a)}var g,h,i,k;g=(a||"").split(",");h=e.cssWatchPeriod||50;e=e.cssNoWait;
i=g.length;for(k=0;k<g.length;k++){var a=g[k],l,a=b.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a);e?(l=U(),l.href=a,J.appendChild(l),d()):ga(a,d,f,h)}},"plugin-builder":"./builder/css",pluginBuilder:"./builder/css"})}).call(this);
(function(B){var x=B.document,v=function(i){for(var t={},i=i.substr(1).split("&"),o=i.length-1;o>=0;o--){var s=i[o].split("=");t[s[0]]=decodeURIComponent((s[1]||"").replace(/\+/g,"%20"))}return t}(location.search),z=function(i){return(i=x.getElementById("disqus-"+i))&&JSON.parse(i.textContent||i.innerHTML)};if(v.n_s)x.documentElement.className+=" not-supported type-"+v.n_s;else{var I=function(){var i=[],t=!1;if(DISQUS.config&&DISQUS.config.switches)for(var o=0,s=DISQUS.config.switches.length;o<s;o++)if(DISQUS.config.switches[o]==
"next_use_jquery"){t=!0;break}t?i.push("js!build/next/lib.js!order"):i.push("js!build/next/lib.ender.js!order");i.push("js!build/next/lounge/client.js!order");i.push("css!build/next/styles/lounge.css");i.push("js!build/next/templates/lounge.js!order");curl(i).then(function(){var i=z("threadData")||z("jsonData");i.code?($("#postCompatContainer").hide(),$("#error").show(),DISQUS.Bus.sendHostMessage("fail",i)):(DISQUS.extend(i.response,z("forumData")),new DISQUS.next.views.Lounge({jsonData:i,el:x.body}),
DISQUS.next.lounge.tracking.init(DISQUS.next.views.Lounge.getInstance()))})};B.onload=function(){curl({baseUrl:B.location.protocol=="https:"?"https://securecdn.disqus.com/1375226634":"http://mediacdn.disqus.com/1375226634"});curl(["js!/next/config.js?forum="+v.f+"!order"]).then(I)}}})(window);